// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcmObM_-x5rWKOQpwYhiVh6yYmg-o8bFs',
    appId: '1:1049195513881:web:ea0533d6a73bf03b678288',
    messagingSenderId: '1049195513881',
    projectId: 'ecommerce-80572',
    authDomain: 'ecommerce-80572.firebaseapp.com',
    storageBucket: 'ecommerce-80572.appspot.com',
    measurementId: 'G-WSLMLVG29B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdEQ6OMsrA1mdIgbTJuomhk2HjuEYSEz0',
    appId: '1:1049195513881:android:4ed74d0832401501678288',
    messagingSenderId: '1049195513881',
    projectId: 'ecommerce-80572',
    storageBucket: 'ecommerce-80572.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-CWabGAZN2sLySIFE1HuCjqseF0GWCfo',
    appId: '1:1049195513881:ios:987ecd87403b664a678288',
    messagingSenderId: '1049195513881',
    projectId: 'ecommerce-80572',
    storageBucket: 'ecommerce-80572.appspot.com',
    iosBundleId: 'com.example.myfirebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-CWabGAZN2sLySIFE1HuCjqseF0GWCfo',
    appId: '1:1049195513881:ios:987ecd87403b664a678288',
    messagingSenderId: '1049195513881',
    projectId: 'ecommerce-80572',
    storageBucket: 'ecommerce-80572.appspot.com',
    iosBundleId: 'com.example.myfirebaseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcmObM_-x5rWKOQpwYhiVh6yYmg-o8bFs',
    appId: '1:1049195513881:web:efcfc57c4be18930678288',
    messagingSenderId: '1049195513881',
    projectId: 'ecommerce-80572',
    authDomain: 'ecommerce-80572.firebaseapp.com',
    storageBucket: 'ecommerce-80572.appspot.com',
    measurementId: 'G-SCJFMJ4F93',
  );

}