// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZvx7Fuf1UNcXUCU9vuTIix4ICsol39_k',
    appId: '1:1002358752578:web:f7a33a8c896d77477234db',
    messagingSenderId: '1002358752578',
    projectId: 'myfirebaseproject-f0acd',
    authDomain: 'myfirebaseproject-f0acd.firebaseapp.com',
    storageBucket: 'myfirebaseproject-f0acd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzUAuF4lhtLe_nHShIZlk7f-cW6Y0T7iU',
    appId: '1:1002358752578:android:2ca079355908a2867234db',
    messagingSenderId: '1002358752578',
    projectId: 'myfirebaseproject-f0acd',
    storageBucket: 'myfirebaseproject-f0acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgBlpL0ZLbxOUTEFqoOiuEHJqf8GOURNI',
    appId: '1:1002358752578:ios:11add58b88ca12bb7234db',
    messagingSenderId: '1002358752578',
    projectId: 'myfirebaseproject-f0acd',
    storageBucket: 'myfirebaseproject-f0acd.appspot.com',
    iosBundleId: 'com.example.myfirebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgBlpL0ZLbxOUTEFqoOiuEHJqf8GOURNI',
    appId: '1:1002358752578:ios:11add58b88ca12bb7234db',
    messagingSenderId: '1002358752578',
    projectId: 'myfirebaseproject-f0acd',
    storageBucket: 'myfirebaseproject-f0acd.appspot.com',
    iosBundleId: 'com.example.myfirebaseproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZvx7Fuf1UNcXUCU9vuTIix4ICsol39_k',
    appId: '1:1002358752578:web:2159dfa0acd3be507234db',
    messagingSenderId: '1002358752578',
    projectId: 'myfirebaseproject-f0acd',
    authDomain: 'myfirebaseproject-f0acd.firebaseapp.com',
    storageBucket: 'myfirebaseproject-f0acd.appspot.com',
  );
}
